config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'user_sessions#new'
  post '/login' => 'user_sessions#create'
  post '/logout' => 'user_sessions#destroy'
  resources :users
  resources :cats do
    resources :contents
  end
  root to: 'catchers#new'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
    validates :name, presence: true
    validates :age, presence: true
    validates :sex, presence: true

    belongs_to :user

    has_many :contents, dependent: :destroy

    mount_uploader :cat_img, ImageUploader
end

app/models/content.rb
class Content < ApplicationRecord
    validates :title, presence: true, length: { maximum: 20 }
    validates :body, presence: true, length: { maximum: 400 }
    validates :content_img, presence: true

    belongs_to :cat
    belongs_to :user

    mount_uploader :content_img, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  has_many :cats, dependent: :destroy
  has_many :contents, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :success, :info, :warning, :danger
end

app/controllers/catchers_controller.rb
class CatchersController < ApplicationController
  def new
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def new
    @cat = Cat.new
  end

  def index
    @cats = Cat.all.includes(:user)
  end

  def create

    @cat = current_user.cats.build(cat_params)
    if @cat.save
      flash[:notice] = 'ネコ情報の登録に成功しました！！'
      redirect_to cats_path
    else
      flash[:danger] = 'ネコ情報の登録に失敗しました。。'
      render new_cat_path
    end
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to cats_path
  end
  private

  def cat_params
    params.require(:cat).permit(:name, :age, :sex, :cat_img)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @cat = Cat.find(params[:cat_id])
    @contents = @cat.contents.all

    @grfdays = @contents.order(start_time: "DESC").limit(10).reverse
    @dayline = Array.new
    @grfdays.each do |grfday|
      @dayline.push(grfday.start_time.strftime('%m/%d').to_s)
    end

    @grafunps = @contents.order(unp: "DESC").limit(10).reverse
    @dayunp = Array.new
    @grafunps.each do |grafunp|
      @dayunp.push(grafunp.unp)
    end

    @grafeats = @contents.order(eat: "DESC").limit(10).reverse
    @dayeat = Array.new
    @grafeats.each do |grafeat|
      @dayeat.push(grafeat.eat)
    end

    @grafweights = @contents.order(weight: "DESC").limit(10).reverse
    @dayweight = Array.new
    @grafweights.each do |grafweight|
      @dayweight.push(grafweight.weight)
    end
  end

  def new
    @cat = Cat.find(params[:cat_id])
    @content = @cat.contents.new
  end

  def show
    @cat = Cat.find(params[:cat_id])
    @content = @cat.contents.find(params[:id])
  end

  def create
    @cat = Cat.find(params[:cat_id])
    @content = @cat.contents.build(content_params)
    @content.user_id = current_user.id
    if @content.save
      flash[:notice] = '日記の投稿に成功したにゃ♪'
      redirect_to cat_contents_path(@cat)
    else
      flash[:danger] = '日記の投稿に失敗したにゃ。。'
      redirect_to new_cat_content_path(@cat)
    end
  end

  def update
  end

  def destroy
  end

  private

  def content_params
    params.require(:content).permit(:title, :unp, :weight, :body, :eat, :content_img, :start_time)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      flash[:notice] = "ログインに成功しました！"
      redirect_to cats_path
    else
      flash[:danger] = "ログインに失敗しました。。"
      redirect_to login_path
    end
  end

  def destroy
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ユーザー登録に成功しました！！"
      redirect_to login_path
    else
      flash[:danger] = "ユーザー登録に失敗しました。。"
      render new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catchers_helper.rb
module CatchersHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/catchers/new.html.slim
h1 Catcher

= link_to '新規登録', new_user_path
= link_to 'ログイン', login_path

app/views/cats/index.html.slim
.row
  .mx-auto
      h1 ネコ一覧

.row
  .mx-auto
    .container
      .row
        - @cats.each do |cat|
          .col-md-4
            .card.border-info.mb-3 style="width: 18rem;"
              - if cat.cat_img.present?
                = image_tag cat.cat_img.url
                .card-body
                  h4.card-title
                    = cat.name
                  p
                    飼い主      #{{cat.user.name}}
                  p
                    年齢  #{{cat.age}}
                  p
                    性別　#{{cat.sex}}
                  .btn.btn-warning
                    = link_to '削除', cat_path(cat), method: :delete
                  .btn.btn-outline-warning
                    = link_to '日記', cat_contents_path(cat.id)

.row
  .mx-auto.btn.btn-warning
    = link_to 'ネコ登録', new_cat_path

app/views/cats/new.html.slim
.row
  .mx-auto
    h1 ネコ登録

.row
  .mx-auto
    = form_with model: @cat do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :age
        = f.select :age, options_for_select((1..25).to_a), class: 'form-control'
      .form-group
        = f.label :sex
        = f.select :sex, ['男の子', '女の子'], {include_blank: '性別を選んでね'}, class: 'form-control'
      .form-group
        = f.label :image
        = f.file_field :cat_img, class: 'form-control'
      = f.submit '登録', class: "btn btn-info"

app/views/contents/index.html.slim
.row
  .mx-auto
    h1 ネコ日記カレンダー🐈

= month_calendar events: @contents do |date, contents|
  = date.day

  - contents.each do |content|
    div
      = link_to content.title, cat_content_path(content.cat_id, content)

.row
  .mx-auto.btn.btn-warning
    = link_to 'ネコ日記新規投稿', new_cat_content_path(@cat)

.row
  .mx-auto
    h1 うんちの回数遷移
<canvas id="myChartUnp", width="400" height="400"></canvas>
javascript:
  var graphdays = #{{@dayline}}, graphunps = #{{@dayunp}};
javascript:
  draw_graph();

.row
  .mx-auto
    h1 ご飯の回数遷移
<canvas id="myChartEat", width="400" height="400"></canvas>
javascript:
  var graphdays = #{{@dayline}}, grapheats = #{{@dayeat}};
javascript:
  draw_graph();

.row
  .mx-auto
    h1 体重の遷移
<canvas id="myChartWeight", width="400" height="400"></canvas>
javascript:
  var graphdays = #{{@dayline}}, graphweights = #{{@dayweight}};
javascript:
  draw_graph();

app/views/contents/new.html.slim
.row
  .mx-auto
    h1 今日のネコ日記

.row
  .mx-auto
    = form_with model: [@cat,@content], local: true do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :unp
        = f.select :unp, options_for_select((1..6).to_a), class: 'form-control'
      .form-group
        = f.label :eat
        = f.select :eat, options_for_select((0..100).to_a), class: 'form-control'
      .form-group
        = f.label :weight
        = f.select :weight, options_for_select((200..500).to_a), class: 'form-control'
      .form-group
        = f.label :body
        = f.text_field :body, class: 'form-control'
      .form-group
        = f.label :start_time
        = f.date_select :start_time, class: 'form-control', use_month_numbers: true
      .form-group
        = f.label :content_img
        = f.file_field :content_img, class: 'form-control'
      = f.submit '登録', class: "btn btn-info"

.row
  .mx-auto.btn.btn-warning
    = link_to '日記一覧', cat_contents_path(@content.cat_id)

app/views/contents/show.html.slim
.row
  .mx-auto
    h1 ネコ日記詳細


.row
  .mx-auto
    .container
      .rows
          .col-md-4
            .card.border-info.mb-3 style="width: 18rem;"
              - if @content.content_img.present?
                = image_tag @content.content_img.url
                .card-body
                  h4.card-title
                    = @content.title
                  p
                    うんちの回数      #{{@content.unp}}回
                  p
                    ご飯の量  #{{@content.eat}}g
                  p
                    体重　#{{@content.weight}}
                  p
                    一言  #{{@content.body}}
                  .btn.btn-outline-warning
                    = link_to '日記一覧', cat_contents_path(@content.cat_id)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Catcher
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - flash.each do |key, value|
      - key = "info" if key == "notice"
      - key = "danger" if key == "alert"
      = content_tag :div, value, class: "arert alert-#{key}"
    = yield

app/views/user_sessions/new.html.slim
.row
  .mx-auto
    h1 ログイン

.row
  .mx-auto
    = form_with url: login_path, method: :post do |f|
      .form-group.text-center.pt-5
        = f.label :email
        = f.text_field :email, class: 'form-control'
      .form-group.text-center.pt-5
        = f.label :password
        = f.password_field :password, class: 'form-control'
      .form-group.text-center.pt-5
        = f.submit "Login", class: "btn btn-info"

= link_to '新規登録', new_user_path

app/views/users/edit.html.slim
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.slim
.row
  .mx-auto
    h1 新規登録

.row
  .mx-auto
    = form_with model: @user, local: true do |f|
      .form-group
        = f.label :name
        = f.text_field :name, class: "form-control"
      .form-group
        = f.label :email
        = f.email_field :email, class: "form-control"
      .form-group
        = f.label :password
        = f.password_field :password, class: "form-control"
      .form-group
        = f.label :password_confirmation
        = f.password_field :password_confirmation, class: "form-control"
      = f.submit '更新', class: "btn btn-info"

= link_to 'タイトル', root_path

app/views/users/show.html.slim
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>